iabbrev tihs this
iabbrev htis this
iabbrev teh the
iabbrev adn and
iabbrev tahn than
iabbrev tehn then
iabbrev waht what
iabbrev leadre leader
iabbrev learde leader
iabbrev leadr leader
cabbrev leadre leader
cabbrev learde leader
cabbrev leadr leader
